"""Model-specific profiles for Dreame wet & dry vacuums."""
from __future__ import annotations

from typing import Any

H15_PRO_HEAT_MODEL = "dreame.hold.w2449e"

# Values decoded from the Dreamehome common plugin/resource package delivered
# for dreame.hold.w2449e, plus UI states verified against the user's H15.
H15_WORK_MODE_MAP = {
    1: "Power on",
    2: "Power off",
    3: "Standby",
    4: "Charging",
    5: "Self-cleaning",
    6: "Self-drying",
    7: "Sleeping",
    8: "Convenient",
    9: "Adding clean water",
    10: "Washing paused",
    11: "Cleaning paused",
    12: "Drying paused",
    13: "OTA upgrading",
    14: "Voice upgrading",
    15: "Charging complete",
    16: "Auto cleaning",
    17: "Degerming",
    18: "Water suction",
    19: "Quiet cleaning",
    20: "Quick cleaning",
    21: "Strong cleaning",
    22: "Personalized cleaning",
    23: "Fast drying",
    24: "Faster drying",
    25: "Quiet drying",
    26: "Fast self-cleaning",
    27: "Deep self-cleaning",
    28: "Smart self-cleaning",
    29: "Convenient paused",
    30: "Fast self-cleaning paused",
    31: "Deep self-cleaning paused",
    32: "Fast self-cleaning drying",
    33: "Deep self-cleaning drying",
    34: "Smart self-cleaning drying",
    35: "Retry drying",
    36: "Retry self-cleaning",
    37: "Smart self-cleaning paused",
    40: "Power mode",
    41: "Hot water cleaning",
    42: "Hot water self-cleaning",
    43: "Hot water self-cleaning paused",
}

H15_SUCTION_MAP = {
    1: "Gentle",
    2: "Standard",
    3: "Strong",
}

H15_WATER_LEVEL_MAP = {
    1: "Low / legacy",
    2: "Standard",
    3: "High",
}

H15_CLEANING_MODE_MAP = {
    1: "Quiet",
    3: "Turbo",
    4: "Personalized",
}

H15_HOT_WATER_MAP = {
    0: "Off",
    1: "Mild",
    2: "Standard",
    3: "Thermal",
}

H15_TRACTION_MAP = {
    0: "Balanced",
    1: "Gentle",
    2: "Turbo",
}

H15_MOISTURE_SENSITIVITY_MAP = {
    2: "Low",
    3: "Medium",
    4: "High",
}

H15_SELF_CLEAN_MODE_MAP = {
    2: "Standard Immersive Self-Cleaning",
    3: "Deep-Clean Immersive Self-Cleaning",
    4: "Smart Self-Cleaning",
    5: "Hot-Water Self-Cleaning",
}

H15_DRY_MODE_MAP = {
    1: "High-Speed",
    3: "Super-Speed",
}

H15_DETERGENT_MODE_MAP = {
    2: "Smart Mode",
    3: "Powerful stain removal",
}

# Known app-facing properties worth probing explicitly even when the broad
# iotstatus cache omits them. This is read-only.
H15_TARGETED_KEYS: tuple[tuple[int, int], ...] = (
    # SIID 1: all properties defined by Dreame's Vacuum model plus the
    # additional w2449e values already observed from cloud/MQTT.
    (1, 1), (1, 2), (1, 3), (1, 4), (1, 6), (1, 7), (1, 8), (1, 9),
    (1, 10), (1, 11), (1, 12), (1, 13), (1, 14), (1, 17),
    (1, 28), (1, 29), (1, 30),
    (1, 33), (1, 34), (1, 35), (1, 36), (1, 47),
    (1, 49), (1, 50), (1, 51), (1, 52),
    (1, 53), (1, 54), (1, 55), (1, 56), (1, 57),
    (1, 64), (1, 65), (1, 66), (1, 67), (1, 68), (1, 69),
    (1, 70), (1, 71), (1, 72), (1, 73),
    (1, 75), (1, 76), (1, 77), (1, 81), (1, 82), (1, 83),

    # Standard/status and warning services.
    (2, 1), (3, 1),
    (4, 1), (4, 2), (4, 3), (4, 5), (4, 6), (4, 7), (4, 38),

    # Consumables / model services defined by the downloaded Dreame plugin.
    (6, 6), (6, 7), (7, 6), (7, 7), (10, 1), (13, 2),
    (16, 1), (16, 2), (16, 3), (16, 4), (16, 6), (16, 7), (16, 8),
    (19, 2), (19, 3),
    (20, 2), (20, 3), (21, 6), (21, 7), (22, 6), (22, 7),
    (23, 1), (24, 1), (25, 1),
    (26, 1), (26, 2), (26, 3), (26, 4), (26, 5),

    # The common plugin also defines a DeviceControl service. The H15 resource
    # disables normal remote control, so these are diagnostic read probes only.
    (100, 1), (100, 2), (100, 3), (100, 4), (100, 5), (100, 6),
)

H15_PROPERTY_META: dict[tuple[int, int], dict[str, Any]] = {
    (1, 1): {
        "name": "Self-cleaning command raw",
        "confidence": "plugin",
        "icon": "mdi:waves-arrow-up",
        "diagnostic": True,
        "note": "Dreame plugin property PropSelfCleaning. Exposed read-only on H15; no write is performed.",
    },
    (1, 2): {
        "name": "Self-drying command raw",
        "confidence": "plugin",
        "icon": "mdi:hair-dryer",
        "diagnostic": True,
        "note": "Dreame plugin property PropSelfDrying. Exposed read-only on H15; no write is performed.",
    },
    (1, 3): {
        "name": "Roller brush head light raw",
        "confidence": "plugin",
        "icon": "mdi:lightbulb-outline",
        "diagnostic": True,
        "note": "Dreame PropLightControl. w2449e resource has brushLight=false, so this is expected to be unsupported/hidden.",
    },
    (1, 4): {
        "name": "Auto detergent mixing raw",
        "confidence": "plugin",
        "icon": "mdi:bottle-tonic-plus-outline",
        "diagnostic": True,
        "note": "Dreame plugin property PropAutoMixDetergent. Read-only until H15 write semantics are verified.",
    },
    (1, 6): {
        "name": "High-level mode raw",
        "confidence": "plugin",
        "icon": "mdi:tune-variant",
        "diagnostic": True,
        "note": "Dreame plugin property PropHighLevelMode.",
    },
    (1, 7): {
        "name": "Return to automatic wash & dry",
        "confidence": "confirmed",
        "icon": "mdi:home-import-outline",
        "diagnostic": False,
        "value_map": {0: "On", 1: "Off"},
        "note": "Dreame plugin property PropAutoBackwash. H15 UI verified raw 1 while Return to Automatic Wash & Dry is off.",
    },
    (1, 8): {
        "name": "Self-cleaning mode",
        "confidence": "plugin",
        "icon": "mdi:waves-arrow-up",
        "diagnostic": False,
        "value_map": H15_SELF_CLEAN_MODE_MAP,
        "note": "Dreame PropSelfCleanWaterMode. Plugin maps 2=Standard Immersive, 3=Deep-Clean Immersive, 4=Smart; 5 is the hot-water self-clean mode.",
    },
    (1, 9): {
        "name": "Auto roller brush drying",
        "confidence": "plugin",
        "icon": "mdi:hair-dryer",
        "diagnostic": False,
        "value_map": {0: "On", 1: "Off"},
        "note": "Dreame PropAutoDrySwitch. App code explicitly treats raw 0 as enabled and writes 0 for On / 1 for Off.",
    },
    (1, 10): {
        "name": "Drying mode",
        "confidence": "confirmed",
        "icon": "mdi:weather-sunny",
        "diagnostic": False,
        "value_map": H15_DRY_MODE_MAP,
        "note": "Dreame PropAutoDryMode. w2449e UI/code maps 1=High-Speed and 3=Super-Speed.",
    },
    (1, 11): {
        "name": "Timed drying after cleaning",
        "confidence": "plugin",
        "icon": "mdi:timer-cog-outline",
        "diagnostic": True,
        "note": "Dreame plugin property PropTimeDryAfterCleanSwitch.",
    },
    (1, 12): {
        "name": "Scheduled drying time raw",
        "confidence": "plugin",
        "icon": "mdi:clock-outline",
        "diagnostic": True,
        "note": "Dreame plugin property PropTimeDryValue.",
    },
    (1, 13): {
        "name": "Scheduled drying repeat raw",
        "confidence": "plugin",
        "icon": "mdi:calendar-sync",
        "diagnostic": True,
        "note": "Dreame plugin property PropTimeDryCircle.",
    },
    (1, 14): {
        "name": "Voice volume",
        "confidence": "plugin",
        "icon": "mdi:volume-high",
        "unit": "%",
        "diagnostic": False,
        "note": "Dreame plugin property PropVolume.",
    },
    (1, 17): {
        "name": "Voice language pack",
        "confidence": "plugin",
        "icon": "mdi:translate",
        "diagnostic": False,
        "note": "Dreame plugin property PropVoicePacketId. The app currently shows English in use.",
    },
    (1, 28): {
        "name": "Work mode",
        "confidence": "confirmed",
        "icon": "mdi:state-machine",
        "diagnostic": False,
        "value_map": H15_WORK_MODE_MAP,
        "note": "Dreame plugin property PropWorkMode. Raw 7 was verified against the app as Sleeping.",
    },
    (1, 29): {
        "name": "Washing level",
        "confidence": "plugin",
        "icon": "mdi:waves",
        "diagnostic": True,
        "note": "Dreame plugin property PropLevelWashing.",
    },
    (1, 30): {
        "name": "Drying level",
        "confidence": "plugin",
        "icon": "mdi:weather-windy",
        "diagnostic": True,
        "note": "Dreame plugin property PropLevelDrying.",
    },
    (1, 47): {
        "name": "Last-clean timestamp candidate",
        "confidence": "candidate",
        "icon": "mdi:clock-outline",
        "diagnostic": True,
        "note": "Raw value has Unix-timestamp shape; keep raw until a controlled cleaning session confirms it.",
    },
    (1, 53): {
        "name": "Total working time",
        "confidence": "plugin",
        "icon": "mdi:timer-outline",
        "diagnostic": True,
        "note": "Dreame plugin property PropTotalTime.",
    },
    (1, 54): {
        "name": "Clean count",
        "confidence": "plugin",
        "icon": "mdi:counter",
        "diagnostic": False,
        "note": "Dreame plugin property PropTotalTimes.",
    },
    (1, 55): {
        "name": "Start time raw",
        "confidence": "plugin",
        "icon": "mdi:clock-start",
        "diagnostic": True,
        "note": "Dreame plugin property PropStartTime.",
    },
    (1, 56): {
        "name": "Total self-dry time raw",
        "confidence": "plugin",
        "icon": "mdi:timer-outline",
        "diagnostic": True,
        "note": "Dreame plugin property PropTotalTimeSelfDry; unit still needs H15 confirmation.",
    },
    (1, 57): {
        "name": "Total self-clean time raw",
        "confidence": "plugin",
        "icon": "mdi:timer-outline",
        "diagnostic": True,
        "note": "Dreame plugin property PropTotalTimeSelfClean; unit still needs H15 confirmation.",
    },
    (1, 64): {
        "name": "Last clean mild-dirt time raw",
        "confidence": "candidate",
        "icon": "mdi:chart-timeline-variant",
        "diagnostic": True,
        "note": "The Dreame CleanLog code reads PIID 64-66 in order for mild/moderate/severe dirt duration. Unit still needs confirmation.",
    },
    (1, 65): {
        "name": "Last clean moderate-dirt time raw",
        "confidence": "candidate",
        "icon": "mdi:chart-timeline-variant",
        "diagnostic": True,
        "note": "The Dreame CleanLog code reads PIID 64-66 in order for mild/moderate/severe dirt duration. Unit still needs confirmation.",
    },
    (1, 66): {
        "name": "Last clean severe-dirt time raw",
        "confidence": "candidate",
        "icon": "mdi:chart-timeline-variant",
        "diagnostic": True,
        "note": "The Dreame CleanLog code reads PIID 64-66 in order for mild/moderate/severe dirt duration. Unit still needs confirmation.",
    },
    (1, 67): {
        "name": "Cleaning solution ratio mode",
        "confidence": "plugin",
        "icon": "mdi:bottle-tonic-plus-outline",
        "diagnostic": False,
        "value_map": H15_DETERGENT_MODE_MAP,
        "note": "Dreame PropDetergentFav. w2449e has allowSterilize=false, so raw 2=Smart Mode and raw 3=Powerful stain removal.",
    },
    (1, 75): {
        "name": "Scheduled wash & dry mode",
        "confidence": "plugin",
        "icon": "mdi:washing-machine",
        "diagnostic": False,
        "note": "Dreame plugin property PropAutoCleanMode.",
    },
    (1, 76): {
        "name": "Scheduled wash & dry start time raw",
        "confidence": "plugin",
        "icon": "mdi:clock-start",
        "diagnostic": True,
        "note": "Dreame plugin property PropTimeCleanValue.",
    },
    (1, 77): {
        "name": "Scheduled wash & dry repeat raw",
        "confidence": "plugin",
        "icon": "mdi:calendar-sync",
        "diagnostic": True,
        "note": "Dreame plugin property PropTimeCleanCircle.",
    },
    (1, 81): {
        "name": "Return self-cleaning wash mode",
        "confidence": "plugin",
        "icon": "mdi:waves-arrow-up",
        "diagnostic": True,
        "note": "Dreame plugin property PropBackSelfCleanWaterMode.",
    },
    (1, 82): {
        "name": "Return self-cleaning dry mode",
        "confidence": "plugin",
        "icon": "mdi:weather-sunny",
        "diagnostic": True,
        "note": "Dreame plugin property PropBackSelfCleanDryMode.",
    },
    (1, 83): {
        "name": "Scheduled self-dry mode",
        "confidence": "plugin",
        "icon": "mdi:calendar-clock",
        "diagnostic": True,
        "note": "Dreame plugin property PropTimeSelfDryMode.",
    },
    (2, 1): {
        "name": "Cloud status code raw",
        "confidence": "candidate",
        "icon": "mdi:state-machine",
        "diagnostic": True,
        "note": "Observed mirroring latestStatus and often 1.28. Kept raw until independent semantics are proven.",
    },
    (3, 1): {
        "name": "Battery",
        "confidence": "confirmed",
        "icon": "mdi:battery",
        "unit": "%",
        "device_class": "battery",
        "state_class": "measurement",
        "diagnostic": False,
        "note": "Confirmed H15 battery percentage.",
    },
    (4, 1): {
        "name": "Warnings raw",
        "confidence": "plugin",
        "icon": "mdi:alert-outline",
        "diagnostic": True,
        "bitfield": True,
        "note": "Dreame plugin property PropWarn. H15 bit meanings remain under test.",
    },
    (4, 2): {
        "name": "Errors raw",
        "confidence": "plugin",
        "icon": "mdi:alert-circle-outline",
        "diagnostic": True,
        "bitfield": True,
        "note": "Dreame plugin property PropError. H15 bit meanings remain under test.",
    },
    (4, 3): {
        "name": "Warning push raw",
        "confidence": "plugin",
        "icon": "mdi:bell-alert-outline",
        "diagnostic": True,
        "bitfield": True,
        "note": "Dreame plugin property PropWarnPush.",
    },
    (4, 5): {
        "name": "Raw 4.5",
        "confidence": "unmapped",
        "icon": "mdi:code-array",
        "diagnostic": True,
        "note": "Observed list value on H15; do not inherit H14 water semantics until verified.",
    },
    (4, 6): {
        "name": "Raw 4.6",
        "confidence": "unmapped",
        "icon": "mdi:code-tags",
        "diagnostic": True,
    },
    (4, 7): {
        "name": "Raw 4.7",
        "confidence": "unmapped",
        "icon": "mdi:code-array",
        "diagnostic": True,
        "note": "Observed list value on H15; do not inherit H14 suction semantics until verified.",
    },
    (4, 38): {
        "name": "Raw 4.38",
        "confidence": "unmapped",
        "icon": "mdi:code-tags",
        "diagnostic": True,
    },
    (6, 6): {
        "name": "Roller brush maximum life raw",
        "confidence": "plugin",
        "icon": "mdi:rotate-right",
        "unit": "min",
        "diagnostic": True,
        "note": "Dreame FrontBrush/PropFrontBrushMaxHeal.",
    },
    (6, 7): {
        "name": "Roller brush remaining",
        "confidence": "confirmed",
        "icon": "mdi:rotate-right",
        "unit": "min",
        "device_class": "duration",
        "state_class": "measurement",
        "diagnostic": False,
        "remaining_time": True,
        "note": "Dreame FrontBrush/PropFrontBrushLeftHeal. App percentage/hours matched the raw minutes.",
    },
    (7, 6): {
        "name": "Rear brush maximum life raw",
        "confidence": "plugin",
        "icon": "mdi:rotate-right",
        "unit": "min",
        "diagnostic": True,
        "note": "Dreame BackBrush/PropBackBrushMaxHeal. Optional service on H15.",
    },
    (7, 7): {
        "name": "Rear brush remaining raw",
        "confidence": "plugin",
        "icon": "mdi:rotate-right",
        "unit": "min",
        "device_class": "duration",
        "diagnostic": True,
        "remaining_time": True,
        "note": "Dreame BackBrush service. H15 currently reports -1, so this accessory is likely unsupported.",
    },
    (10, 1): {
        "name": "Dip angle level",
        "confidence": "plugin",
        "icon": "mdi:angle-acute",
        "diagnostic": True,
        "note": "Dreame plugin property PropDipAngleLevel.",
    },
    (16, 1): {
        "name": "Suction setting",
        "confidence": "confirmed",
        "icon": "mdi:fan",
        "diagnostic": False,
        "value_map": H15_SUCTION_MAP,
        "note": "Dreame PropCleanPower. H15 UI: Gentle/Standard/Strong.",
    },
    (16, 2): {
        "name": "Water level",
        "confidence": "confirmed",
        "icon": "mdi:water",
        "diagnostic": False,
        "value_map": H15_WATER_LEVEL_MAP,
        "note": "Dreame PropCleanWater. H15 UI exposes Standard and High; value 1 is retained as legacy/low until observed.",
    },
    (16, 6): {
        "name": "Personalized mode flag",
        "confidence": "plugin",
        "icon": "mdi:tune-variant",
        "diagnostic": True,
        "note": "Dreame PropCustomSwitch.",
    },
    (16, 7): {
        "name": "Cleaning mode",
        "confidence": "confirmed",
        "icon": "mdi:broom",
        "diagnostic": False,
        "value_map": H15_CLEANING_MODE_MAP,
        "note": "Dreame internal PropVoiceName; w2449e resource enables correctPropVoiceName. H15 UI maps 1=Quiet, 3=Turbo, 4=Personalized.",
    },
    (16, 8): {
        "name": "Hot water mode",
        "confidence": "confirmed",
        "icon": "mdi:water-thermometer",
        "diagnostic": False,
        "value_map": H15_HOT_WATER_MAP,
        "note": "Dreame PropCustomHotWaterMode. H15 UI: Off/Mild/Standard/Thermal.",
    },
    (13, 2): {
        "name": "Electrolyzed water setting raw",
        "confidence": "plugin",
        "icon": "mdi:flash-outline",
        "diagnostic": True,
        "note": "Dreame ElectrolyzedWater/PropElectrolyzedWaterSwitch. w2449e resource disables this setting in the UI.",
    },
    (16, 3): {
        "name": "Electrolyzed water raw",
        "confidence": "plugin",
        "icon": "mdi:flash-outline",
        "diagnostic": True,
        "note": "Dreame VacuumExtend/PropElecWater. w2449e does not expose the electrolyzed-water setting in its UI.",
    },
    (16, 4): {
        "name": "Brush speed raw",
        "confidence": "plugin",
        "icon": "mdi:rotate-right",
        "diagnostic": True,
        "note": "Dreame VacuumExtend/PropBrushSpeed. Not shown in the current H15 UI.",
    },
    (19, 2): {
        "name": "Filter maximum life raw",
        "confidence": "plugin",
        "icon": "mdi:air-filter",
        "unit": "min",
        "diagnostic": True,
        "note": "Dreame Filter/PropFilterMaxHeal.",
    },
    (19, 3): {
        "name": "Filter remaining",
        "confidence": "confirmed",
        "icon": "mdi:air-filter",
        "unit": "min",
        "device_class": "duration",
        "state_class": "measurement",
        "diagnostic": False,
        "remaining_time": True,
        "note": "Dreame Filter/PropFilterLeftHeal. App percentage/hours matched the raw minutes.",
    },
    (20, 2): {
        "name": "Dust bag maximum life raw",
        "confidence": "plugin",
        "icon": "mdi:sack-outline",
        "unit": "min",
        "diagnostic": True,
        "note": "Dreame DustBag/PropDustBagMaxHeal. Optional service; not currently observed on this H15.",
    },
    (20, 3): {
        "name": "Dust bag remaining raw",
        "confidence": "plugin",
        "icon": "mdi:sack-outline",
        "unit": "min",
        "diagnostic": True,
        "note": "Dreame DustBag/PropDustBagLeftHeal. Optional service; not currently observed on this H15.",
    },
    (21, 6): {
        "name": "Suction brush maximum life raw",
        "confidence": "plugin",
        "icon": "mdi:rotate-right",
        "unit": "min",
        "diagnostic": True,
        "note": "Dreame SuckBrush/PropSuckBrushMaxHeal. Optional service.",
    },
    (21, 7): {
        "name": "Suction brush remaining raw",
        "confidence": "plugin",
        "icon": "mdi:rotate-right",
        "unit": "min",
        "diagnostic": True,
        "note": "Dreame SuckBrush/PropSuckBrushLeftHeal. Optional service.",
    },
    (22, 6): {
        "name": "Suction filter maximum life raw",
        "confidence": "plugin",
        "icon": "mdi:air-filter",
        "unit": "min",
        "diagnostic": True,
        "note": "Dreame SuckFilter/PropSuckFilterMaxHeal. Optional service.",
    },
    (22, 7): {
        "name": "Suction filter remaining raw",
        "confidence": "plugin",
        "icon": "mdi:air-filter",
        "unit": "min",
        "diagnostic": True,
        "note": "Dreame SuckFilter/PropSuckFilterLeftHeal. Optional service.",
    },
    (23, 1): {
        "name": "GlideWheel traction",
        "confidence": "plugin",
        "icon": "mdi:car-traction-control",
        "diagnostic": False,
        "value_map": H15_TRACTION_MAP,
        "note": "Dreame Wheel/PropPowerWheel. App code maps raw 1=Gentle, 0=Balanced, 2=Turbo.",
    },
    (24, 1): {
        "name": "Lifting robotic arm modes raw",
        "confidence": "plugin",
        "icon": "mdi:robot-industrial-outline",
        "diagnostic": False,
        "decoder": "mechanical_arm_2449",
        "note": "Dreame MechanicalArm/PropMechanicalArmSwitch. w2449e uses inverted bits: bit0 Smart, bit3 Hot Water, bit2 Suction, bit4 Custom; 0 means selected. Bit1 is unused by the w2449e UI.",
    },
    (25, 1): {
        "name": "Global hot water mode raw",
        "confidence": "candidate",
        "icon": "mdi:water-thermometer-outline",
        "diagnostic": True,
        "note": "Dreame HotWater/PropGlobalHotWaterMode. Not yet observed in the H15 cache.",
    },
    (26, 1): {
        "name": "Smart drying",
        "confidence": "plugin",
        "icon": "mdi:weather-sunny-alert",
        "diagnostic": False,
        "value_map": {0: "On", 1: "Off"},
        "note": "Dreame Smart/PropSmartDrySwitch at 26.1. App code treats raw 0 as Smart Drying enabled.",
    },
    (26, 2): {
        "name": "Smart moisture protection",
        "confidence": "plugin",
        "icon": "mdi:water-sync",
        "diagnostic": False,
        "value_map": {0: "On", 1: "Off"},
        "note": "Dreame Smart/PropSmartReDrySwitch at 26.2. App code treats raw 0 as Smart Moisture Protection enabled.",
    },
    (26, 3): {
        "name": "Roller brush moisture sensitivity",
        "confidence": "plugin",
        "icon": "mdi:water-percent",
        "diagnostic": False,
        "value_map": H15_MOISTURE_SENSITIVITY_MAP,
        "note": "Dreame Smart/PropSmartDryRate at 26.3. App slider writes raw 2=Low, 3=Medium, 4=High.",
    },
    (26, 4): {
        "name": "Raw 26.4",
        "confidence": "unmapped",
        "icon": "mdi:code-tags",
        "diagnostic": True,
    },
    (26, 5): {
        "name": "Raw 26.5",
        "confidence": "unmapped",
        "icon": "mdi:code-tags",
        "diagnostic": True,
    },
    (100, 1): {
        "name": "Remote forward raw",
        "confidence": "plugin",
        "icon": "mdi:arrow-up",
        "diagnostic": True,
        "note": "Dreame DeviceControl/PropDeviceControlFront. w2449e has isSupportControl=false; diagnostic read only.",
    },
    (100, 2): {
        "name": "Remote backward raw",
        "confidence": "plugin",
        "icon": "mdi:arrow-down",
        "diagnostic": True,
        "note": "Dreame DeviceControl/PropDeviceControlBack. w2449e has isSupportControl=false; diagnostic read only.",
    },
    (100, 3): {
        "name": "Remote left raw",
        "confidence": "plugin",
        "icon": "mdi:arrow-left",
        "diagnostic": True,
        "note": "Dreame DeviceControl/PropDeviceControlLeft. w2449e has isSupportControl=false; diagnostic read only.",
    },
    (100, 4): {
        "name": "Remote right raw",
        "confidence": "plugin",
        "icon": "mdi:arrow-right",
        "diagnostic": True,
        "note": "Dreame DeviceControl/PropDeviceControlRight. w2449e has isSupportControl=false; diagnostic read only.",
    },
    (100, 5): {
        "name": "Remote left-back raw",
        "confidence": "plugin",
        "icon": "mdi:arrow-bottom-left",
        "diagnostic": True,
        "note": "Dreame DeviceControl/PropDeviceControlLeftBack. w2449e has isSupportControl=false; diagnostic read only.",
    },
    (100, 6): {
        "name": "Remote right-back raw",
        "confidence": "plugin",
        "icon": "mdi:arrow-bottom-right",
        "diagnostic": True,
        "note": "Dreame DeviceControl/PropDeviceControlRightBack. w2449e has isSupportControl=false; diagnostic read only.",
    },
}


def is_h15_pro_heat(model: str | None) -> bool:
    """Return whether a device uses the H15 Pro Heat profile."""
    return str(model or "").lower() == H15_PRO_HEAT_MODEL
